### ISSUE TITLE
Instruction of set up project in Eclipse

### ISSUE THREAD

**Issue by malsolec** [autyzm-pg/mroza#36]
# **ENG**:
### **Actual**:

TODO
### **Expected**:

TODO
# **PL:**
### **Stan obecny:**

Brak instrukcji dla Eclipse.
### **Stan oczekiwany:**.

Stworzenie instrukcji konfiguracji środowiska dla Eclipse.

**Comment by Ro-Ze** [comment]
Since GitHub doesn't seem to provide an easy way (at least I couldn't find any) to create pull request for wiki pages, I just post link to forked wiki here:
https://github.com/Ro-Ze/mroza/wiki/Eclipse-project-setup
It's still needs some improvements, but overall view is there. Let me know what you think about this.

**Comment by malsolec** [comment]
Your instruction is great. It is nice and clear. But I think, we should consider if we keep instructions on wiki or in file on repo. Wiki seems to be great place for it, however pull request are easier for files on repo. Let's discuss it on [forum ](http://autyzm.eti.pg.gda.pl/forum/)

**Comment by malsolec** [comment]
Merged to wiki master:)
